-- ============================================================
-- DUROMAX AFTER-SALES — COMPLETE DATABASE SCHEMA
-- Run this entire block in Supabase SQL Editor
-- ============================================================

-- Auto-incrementing counter for readable ticket numbers
create sequence if not exists ticket_seq start 1;

-- ── TABLE 1: PROFILES ────────────────────────────────────────
-- One row per staff member. Created automatically when a user
-- signs up via Supabase Auth (see trigger at the bottom).
create table if not exists profiles (
  id          uuid references auth.users on delete cascade primary key,
  full_name   text not null default 'New User',
  mobile      text,
  role        text not null default 'installer'
                check (role in ('admin', 'supervisor', 'accounts')),
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

-- ── TABLE 2: TICKETS ─────────────────────────────────────────
-- Every customer service request is one row here.
-- This is the central table everything else links to.
create table if not exists tickets (
  id                    uuid not null default gen_random_uuid() primary key,

  -- Human-readable ID like DM-2026-0001 (auto-generated by trigger)
  ticket_number         text unique,

  -- Customer details (no account, just data)
  client_name           text not null,
  client_mobile         text not null,  -- also used for tracking verification
  site_address          text not null,
  complaint_description text not null,
  brand_installed       text,
  duromax_installation  boolean,
  preferred_slot        text,           -- 'morning' | 'afternoon' | 'evening'
  photo_url             text,           -- optional photo from Supabase Storage

  -- Pricing flag set by admin when raising invoice
  is_outstation         boolean not null default false,

  -- The core status field — drives everything
  status  text not null default 'new'
    check (status in (
      'new',              -- customer submitted the form
      'invoiced',         -- admin raised ₹3,000 visit fee invoice
      'paid',             -- visit fee paid via Razorpay
      'scheduled',        -- admin assigned a supervisor
      'visited',          -- supervisor submitted site report
      'parts_invoiced',   -- admin raised spare parts invoice
      'parts_paid',       -- customer paid spare parts invoice
      'closed'            -- admin marked ticket as done
    )),

  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- ── TABLE 3: PAYMENTS ────────────────────────────────────────
-- Tracks both the ₹3,000 visit fee AND the spare parts payment.
-- Each gets its own row with its own signed token for the pay link.
create table if not exists payments (
  id                    uuid not null default gen_random_uuid() primary key,
  ticket_id             uuid not null references tickets on delete cascade,

  -- visit_fee = first payment | spare_parts = second payment
  payment_type          text not null check (payment_type in ('visit_fee', 'spare_parts')),

  -- UUID token for the /pay/[token] URL. One-time, expires in 48h.
  token                 uuid not null default gen_random_uuid() unique,
  token_expires_at      timestamptz not null default (now() + interval '48 hours'),

  -- Razorpay fields — filled when order is created and webhook fires
  razorpay_order_id     text,
  razorpay_payment_id   text,           -- filled by webhook on success

  -- Amount stored in paise (₹3,000 = 300000, ₹4,500 = 450000)
  amount_paise          integer not null,

  status  text not null default 'pending'
    check (status in ('pending', 'paid', 'failed', 'expired')),

  paid_at     timestamptz,              -- filled by webhook
  created_at  timestamptz not null default now()
);

-- ── TABLE 4: SUPERVISOR ALLOCATIONS ──────────────────────────
create table if not exists supervisor_allocations (
  id              uuid not null default gen_random_uuid() primary key,
  ticket_id       uuid not null references tickets on delete cascade unique,
  supervisor_id   uuid not null references profiles,
  allocated_by    uuid not null references profiles,  -- the admin who assigned
  visit_date      date not null,
  time_slot       text not null,        -- e.g. '10:00–12:00 AM'
  notes           text,                 -- optional notes for supervisor
  allocated_at    timestamptz not null default now(),

  -- SLA: admin must assign within 48h of payment
  sla_deadline    timestamptz not null default (now() + interval '48 hours'),
  sla_alerted     boolean not null default false  -- true once breach email sent
);

-- ── TABLE 5: SITE VISITS ─────────────────────────────────────
-- Supervisor fills this form during their on-site visit.
create table if not exists site_visits (
  id                  uuid not null default gen_random_uuid() primary key,
  ticket_id           uuid not null references tickets on delete cascade unique,
  supervisor_id       uuid not null references profiles,
  visit_date          date not null,
  client_complaint    text not null,    -- what the customer told them
  observed_issue      text not null,    -- what the supervisor actually found
  urgency_level       text default 'medium' check (urgency_level in ('low', 'medium', 'high')),
  est_repair_time     text,             -- free text, e.g. '2–3 hours'
  warranty_status     text,             -- 'within' | 'expired' | 'not_duromax'
  supervisor_signed   boolean not null default false,
  client_signed       boolean not null default false,
  remarks             text,
  submitted_at        timestamptz not null default now()
);

-- ── TABLE 6: SPARE PARTS ─────────────────────────────────────
-- Each row is one part in the site visit report.
-- Child of site_visits.
create table if not exists spare_parts (
  id              uuid not null default gen_random_uuid() primary key,
  site_visit_id   uuid not null references site_visits on delete cascade,
  s_no            integer not null,         -- row number (1, 2, 3…)
  article_name    text not null,
  article_number  text,
  quantity        integer not null default 1,
  unit_price_paise integer,                 -- optional, for invoice calculation
  remarks         text
);

-- ── TABLE 7: FEEDBACK ────────────────────────────────────────
-- Optional post-closure feedback from customer.
-- Has its own token so the link can be sent via WhatsApp without login.
create table if not exists feedback (
  id                   uuid not null default gen_random_uuid() primary key,
  ticket_id            uuid not null references tickets on delete cascade unique,

  -- UUID token for /feedback/[token] URL
  token                uuid not null default gen_random_uuid() unique,
  token_used           boolean not null default false,  -- prevent double submit

  -- Ratings all 1–5
  overall_rating       integer check (overall_rating between 1 and 5),
  supervisor_rating    integer check (supervisor_rating between 1 and 5),
  quality_rating       integer check (quality_rating between 1 and 5),
  timeliness_rating    integer check (timeliness_rating between 1 and 5),
  comment              text,
  submitted_at         timestamptz
);

-- ── TABLE 8: NOTIFICATION LOG ────────────────────────────────
-- Every WhatsApp message and email we send gets logged here.
-- Useful for debugging and re-send logic.
create table if not exists notification_log (
  id              uuid not null default gen_random_uuid() primary key,
  ticket_id       uuid references tickets on delete set null,
  channel         text not null check (channel in ('whatsapp', 'email', 'sms')),
  recipient       text not null,        -- phone number or email address
  template_name   text not null,        -- e.g. 'invoice_raised'
  status          text not null default 'sent' check (status in ('sent', 'failed')),
  error_message   text,                 -- filled if status = 'failed'
  sent_at         timestamptz not null default now()
);

-- ============================================================
-- AUTOMATIC BEHAVIOURS — Triggers & Functions
-- ============================================================

-- 1. Auto-generate ticket number like DM-2026-0001
create or replace function generate_ticket_number()
returns trigger
language plpgsql
as $$
begin
  new.ticket_number :=
    'DM-' ||
    to_char(now(), 'YYYY') || '-' ||
    lpad(nextval('ticket_seq')::text, 4, '0');
  return new;
end;
$$;

drop trigger if exists set_ticket_number on tickets;
create trigger set_ticket_number
  before insert on tickets
  for each row
  execute function generate_ticket_number();

-- 2. Auto-update updated_at whenever a ticket row changes
create or replace function touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists tickets_updated_at on tickets;
create trigger tickets_updated_at
  before update on tickets
  for each row
  execute function touch_updated_at();

-- 3. Auto-create a profiles row when a new staff member is added
--    in Supabase Auth (works for both email and phone sign-up)
create or replace function handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into profiles (id, full_name, mobile, role)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'full_name', 'New User'),
    coalesce(new.phone, new.raw_user_meta_data->>'mobile'),
    coalesce(new.raw_user_meta_data->>'role', 'admin')
  )
  on conflict (id) do nothing;  -- safe to call multiple times
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row
  execute function handle_new_user();

-- ============================================================
-- ROW LEVEL SECURITY
-- Each role only sees and touches what they need to.
-- ============================================================

alter table profiles               enable row level security;
alter table tickets                enable row level security;
alter table payments               enable row level security;
alter table supervisor_allocations enable row level security;
alter table site_visits            enable row level security;
alter table spare_parts            enable row level security;
alter table feedback               enable row level security;
alter table notification_log       enable row level security;

-- Helper function: returns the role of the currently logged-in user
-- without causing a recursive RLS check.
create or replace function current_user_role()
returns text
language sql
security definer stable
as $$
  select role from profiles where id = auth.uid();
$$;

-- ── PROFILES policies ──
-- Each user reads their own profile
create policy "read own profile"
  on profiles for select
  using (id = auth.uid());

-- Admin can read and manage all profiles
create policy "admin manages profiles"
  on profiles for all
  using (current_user_role() = 'admin');

-- ── TICKETS policies ──
-- Anyone (including unauthenticated) can submit a new ticket
create policy "public can submit ticket"
  on tickets for insert
  with check (true);

-- Anyone can read a ticket to support tracking
-- (the actual mobile verification is done in the API route, not RLS)
create policy "public can read ticket for tracking"
  on tickets for select
  using (true);

-- Admin and accounts can update any ticket
create policy "admin accounts update tickets"
  on tickets for update
  using (current_user_role() in ('admin', 'accounts'));

-- Supervisor can read tickets assigned to them
create policy "supervisor reads own tickets"
  on tickets for select
  using (
    exists (
      select 1 from supervisor_allocations sa
      where sa.ticket_id = tickets.id
        and sa.supervisor_id = auth.uid()
    )
  );

-- ── PAYMENTS policies ──
-- Public can read a payment row by token (for the pay page)
-- Actual token validation done in API route
create policy "public reads payment by token"
  on payments for select
  using (true);

-- Admin and accounts can manage all payments
create policy "admin accounts manage payments"
  on payments for all
  using (current_user_role() in ('admin', 'accounts'));

-- ── SUPERVISOR ALLOCATIONS policies ──
create policy "admin manages supervisor allocations"
  on supervisor_allocations for all
  using (current_user_role() = 'admin');

create policy "supervisor reads own allocation"
  on supervisor_allocations for select
  using (supervisor_id = auth.uid());

-- ── SITE VISITS policies ──
create policy "admin accounts manage visits"
  on site_visits for all
  using (current_user_role() in ('admin', 'accounts'));

create policy "supervisor manages own visits"
  on site_visits for all
  using (supervisor_id = auth.uid());

-- ── SPARE PARTS policies ──
create policy "admin accounts manage parts"
  on spare_parts for all
  using (current_user_role() in ('admin', 'accounts'));

create policy "supervisor manages own parts"
  on spare_parts for all
  using (
    exists (
      select 1 from site_visits sv
      where sv.id = site_visit_id
        and sv.supervisor_id = auth.uid()
    )
  );

-- ── FEEDBACK policies ──
-- Anyone can submit feedback via token (validated in API route)
create policy "public submits feedback"
  on feedback for insert
  with check (true);

create policy "public reads feedback token"
  on feedback for select
  using (true);

create policy "admin updates feedback"
  on feedback for update
  using (current_user_role() in ('admin', 'accounts'));

-- ── NOTIFICATION LOG policies ──
create policy "admin reads notification log"
  on notification_log for select
  using (current_user_role() in ('admin', 'accounts'));

create policy "service inserts notification log"
  on notification_log for insert
  with check (true);

-- ============================================================
-- STORAGE BUCKETS
-- ============================================================
insert into storage.buckets (id, name, public)
values ('ticket-photos', 'ticket-photos', false)
on conflict (id) do nothing;

insert into storage.buckets (id, name, public)
values ('invoices', 'invoices', false)
on conflict (id) do nothing;

-- Allow authenticated uploads to ticket-photos
create policy "authenticated upload ticket photos"
  on storage.objects for insert
  with check (bucket_id = 'ticket-photos');

create policy "admin reads ticket photos"
  on storage.objects for select
  using (bucket_id = 'ticket-photos' and current_user_role() in ('admin', 'accounts', 'supervisor'));
